{% set name = "tblite-python" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tblite/tblite/releases/download/v{{ version }}/tblite-{{ version }}.tar.gz
  sha256: 48654770b2681a354d9f6a849c5bc903b94a18c39c25c61754807d8add1ad7a9

build:
  number: 1
  skip: true  # [win]


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - cffi                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - meson                               # [build_platform != target_platform]
    - pkg-config                          # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - cffi
    - meson
    - pkg-config
    - pip
    - python
    - tblite >={{ version }}
  run:
    - cffi
    - numpy
    - python


test:
  imports:
    - tblite
    - tblite.library
    - tblite.interface
  requires:
    - pip
    - pytest
    - ase
  commands:
    - pip check
    - pytest --pyargs tblite -vv

about:
  home: https://pypi.org/project/tblite
  dev_url: https://github.com/tblite/tblite
  doc_url: https://tblite.readthedocs.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - subprojects/tblite/COPYING
    - subprojects/tblite/COPYING.LESSER
  summary: Python API for the tblite project

extra:
  recipe-maintainers:
    - awvwgk
